import { restoreProject, serializeProject } from "./document";
import { sampleProjectDocument } from "./templates";
import type { MatchforgeProject, SceneDocument, SceneLayer } from "./types";
export const PROJECT_KEY="matchforge.editor.project.v1"; export const TEMPLATE_OPEN_KEY="matchforge.editor.openTemplate.v1";
export interface LoadProjectResult { project: MatchforgeProject; error: string | null; restored:boolean; }
export function cloneProject(project:MatchforgeProject, name=project.name): MatchforgeProject { const stamp=Date.now(); return {...project,id:`project-${stamp}`,name,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),scenes:project.scenes.map((s,i)=>cloneScene(s,`scene-${stamp}-${i}`)),activeSceneId:`scene-${stamp}-0`}; }
export function cloneScene(scene:SceneDocument, id=`${scene.id}-copy-${Date.now()}`): SceneDocument { const layerMap=(l:SceneLayer,idx:number):SceneLayer=>({...l,id:`${l.id}-copy-${Date.now()}-${idx}`,name:l.name.includes("copy")?l.name:`${l.name} copy`}) as SceneLayer; return {...scene,id,metadata:{...scene.metadata,title:scene.metadata.title.includes("copy")?scene.metadata.title:`${scene.metadata.title} copy`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},layers:scene.layers.map(layerMap)}; }
export function loadProject(storage:Pick<Storage,"getItem">=localStorage):LoadProjectResult{ const raw=storage.getItem(PROJECT_KEY); if(!raw)return {project:sampleProjectDocument,error:null,restored:false}; const restored=restoreProject(raw); if(restored.success&&restored.data)return {project:restored.data,error:null,restored:true}; return {project:sampleProjectDocument,error:`Invalid stored project: ${restored.errors.join(" ")}`,restored:false}; }
export function saveProject(project:MatchforgeProject, storage:Pick<Storage,"setItem">=localStorage){ storage.setItem(PROJECT_KEY, serializeProject(project)); }
export function projectWithScene(project:MatchforgeProject, scene:SceneDocument):MatchforgeProject{ const exists=project.scenes.some((s)=>s.id===scene.id); const scenes=exists?project.scenes.map((s)=>s.id===scene.id?scene:s):[...project.scenes,scene]; return {...project,scenes,activeSceneId:scene.id,updatedAt:new Date().toISOString()}; }
